#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CaterinaShopMobileApp.Resource", IsApplication=true)]

namespace CaterinaShopMobileApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int maxScaleFactor = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int minScaleFactor = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int light_green = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int green_item_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int green_selector_actionbar_first = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_moreoverflow_normal_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int image_view_gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int shopIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int spinner_default_holo_light = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int aboutApp = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int imageView = 2131296263;
			
			// aapt resource value: 0x7f090013
			public const int itemPopupMenu = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int itemShowAbout = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int itemShowShopWebSite = 2131296276;
			
			// aapt resource value: 0x7f090001
			public const int lblAboutAppText = 2131296257;
			
			// aapt resource value: 0x7f09000d
			public const int lblCloth = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int lblClothText = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int lblColor = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int lblColorText = 2131296272;
			
			// aapt resource value: 0x7f09000b
			public const int lblManufacture = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int lblManufactureText = 2131296268;
			
			// aapt resource value: 0x7f090011
			public const int lblPrice = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int lblPriceText = 2131296274;
			
			// aapt resource value: 0x7f090009
			public const int lblSizes = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int lblSizesText = 2131296266;
			
			// aapt resource value: 0x7f090002
			public const int main = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int pager = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int pagerTabStrip = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int scrollableImageView = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int showDetailLayout = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int tableLayout1 = 2131296264;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutApp = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ShowDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewPagerFragment = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int Main_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Popup_menu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000d
			public const int aboutAppTitle = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int actionBarTitle = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int errorDlgTitle = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int lblAboutAppText = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int lblCloth = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int lblColor = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int lblManufacture = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int lblPrice = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int lblSizes = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int mainTitle = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int progressDlgMessage = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int showAbout = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int showPopupMenu = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int showShopWebSite = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int MyAlertDialog = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int MyAlertDialogTitle = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int TableItemEven = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int TableItemOdd = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Theme_Holo_Light_Dialog_Green = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int Theme_Holo_Light_Green = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int Theme_MyDropDownNav = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Theme_MyListView = 2131165190;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ScrollableImageView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int ScrollableImageView_maxScaleFactor = 1;
			
			// aapt resource value: 0
			public const int ScrollableImageView_minScaleFactor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
